version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres2
    restart: always
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
