spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/department-service
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    jpa:
      ddl: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: create
      show-sql: true
  application:
    name: department-service
  config:
    import: "optional:configserver:http://localhost:8088"

