spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/your_database_name
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
  application:
    name: department-service
  config:
    import: "optional:configserver:http://localhost:8088"

